// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoPruebaAleix.Infrastructure;

namespace ProyectoPruebaAleix.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220619230105_SeedInitialData")]
    partial class SeedInitialData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProyectoPruebaAleix.Domain.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nif")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ClientId");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            ClientId = 1,
                            Apellidos = "Jimenez Pato",
                            Email = "paco.jimenez@hotmail.com",
                            Nif = "453453254P",
                            Nombre = "Paco"
                        },
                        new
                        {
                            ClientId = 2,
                            Apellidos = "Garcia De Mato",
                            Email = "carladm@gmail.com",
                            Nif = "456345654O",
                            Nombre = "Carla"
                        },
                        new
                        {
                            ClientId = 3,
                            Apellidos = "Sanchez Martin",
                            Email = "ramon55@gmail.com",
                            Nif = "342342412Y",
                            Nombre = "Ramon"
                        },
                        new
                        {
                            ClientId = 4,
                            Apellidos = "Loro Ayuso",
                            Email = "lorito@gmail.com",
                            Nif = "821378223Y",
                            Nombre = "Irene"
                        },
                        new
                        {
                            ClientId = 5,
                            Apellidos = "Lorenzo Marquez",
                            Email = "lorenzo@gmail.com",
                            Nif = "456542342I",
                            Nombre = "Alex"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
